/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-16 13:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <footer id=\"footer\" class=\"footer\" data-bg-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/footer-bg.png\" data-bg-color=\"#262E3B\">\r\n");
      out.write("    <div class=\"container pt-70 pb-40\">\r\n");
      out.write("      <div class=\"row multi-row-clearfix\">\r\n");
      out.write("        <div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"widget dark\"> <img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/test.png\">\r\n");
      out.write("            <!-- <p class=\"font-12 mt-20 mb-10\">Medinova is a library of Crowdfunding and Medinova templates with predefined elements which helps you to build your own site. Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("            <a class=\"text-gray font-12\" href=\"#\"><i class=\"fa fa-angle-double-right text-theme-colored\"></i> Read more</a>\r\n");
      out.write("            <ul class=\"styled-icons icon-dark mt-20\">\r\n");
      out.write("              <li><a href=\"#\" data-bg-color=\"#3B5998\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\" data-bg-color=\"#02B0E8\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\" data-bg-color=\"#05A7E3\"><i class=\"fa fa-skype\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\" data-bg-color=\"#A11312\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\" data-bg-color=\"#C22E2A\"><i class=\"fa fa-youtube\"></i></a></li>\r\n");
      out.write("            </ul -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- <div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"widget dark\">\r\n");
      out.write("            <h5 class=\"widget-title line-bottom\">Pages</h5>\r\n");
      out.write("            <ul class=\"list list-border\">\r\n");
      out.write("              <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("              <li><a href=\"#\">Services</a></li>\r\n");
      out.write("              <li><a href=\"#\">Experts</a></li>\r\n");
      out.write("              <li><a href=\"#\">Gallery</a></li>\r\n");
      out.write("              <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("              <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"widget dark\">\r\n");
      out.write("            <h5 class=\"widget-title line-bottom\">Quick Links</h5>\r\n");
      out.write("            <ul class=\"list-border list theme-colored angle-double-right\">\r\n");
      out.write("              <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("              <li><a href=\"#\">Donor Privacy Policy</a></li>\r\n");
      out.write("              <li><a href=\"#\">Disclaimer</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("              <li><a href=\"#\">Copyright Notice</a></li>\r\n");
      out.write("              <li><a href=\"#\">Media Center</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> -->\r\n");
      out.write("        <!-- <div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"widget dark\">\r\n");
      out.write("            <h5 class=\"widget-title line-bottom\">Quick Contact</h5>\r\n");
      out.write("            <ul class=\"list list-border\">\r\n");
      out.write("              <li><a href=\"#\">+(012) 345 6789</a></li>\r\n");
      out.write("              <li><a href=\"#\">hello@yourdomain.com</a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"lineheight-20\">121 King Street, Melbourne Victoria 3000, Australia</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p class=\"text-white mb-5 mt-20\">Subscribe to our newsletter</p>\r\n");
      out.write("            <form id=\"footer-mailchimp-subscription-form\" class=\"newsletter-form mt-15\">\r\n");
      out.write("              <label class=\"display-block\" for=\"mce-EMAIL\"></label>\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("                <input type=\"email\" value=\"\" name=\"EMAIL\" placeholder=\"Your Email\"  class=\"form-control\" data-height=\"37px\" id=\"mce-EMAIL\">\r\n");
      out.write("                <span class=\"input-group-btn\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-colored btn-theme-colored font-14 m-0\"><i class=\"fa fa-paper-plane-o text-white\"></i></button>\r\n");
      out.write("                </span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            Mailchimp Subscription Form Validation\r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("              $('#footer-mailchimp-subscription-form').ajaxChimp({\r\n");
      out.write("                  callback: mailChimpCallBack,\r\n");
      out.write("                  url: '//thememascot.us9.list-manage.com/subscribe/post?u=a01f440178e35febc8cf4e51f&amp;id=49d6d30e1e'\r\n");
      out.write("              });\r\n");
      out.write("\r\n");
      out.write("              function mailChimpCallBack(resp) {\r\n");
      out.write("                  // Hide any previous response text\r\n");
      out.write("                  var $mailchimpform = $('#footer-mailchimp-subscription-form'),\r\n");
      out.write("                      $response = '';\r\n");
      out.write("                  $mailchimpform.children(\".alert\").remove();\r\n");
      out.write("                  if (resp.result === 'success') {\r\n");
      out.write("                      $response = '<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>' + resp.msg + '</div>';\r\n");
      out.write("                  } else if (resp.result === 'error') {\r\n");
      out.write("                      $response = '<div class=\"alert alert-danger\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>' + resp.msg + '</div>';\r\n");
      out.write("                  }\r\n");
      out.write("                  $mailchimpform.prepend($response);\r\n");
      out.write("              }\r\n");
      out.write("            </script>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-bottom\" data-bg-color=\"#242730\">\r\n");
      out.write("      <div class=\"container pt-15 pb-15\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <p class=\"font-12 text-black-777 m-0 sm-text-center\">Copyright &copy;2020 술:정(井). All Rights Reserved</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- <div class=\"col-md-6 text-right\">\r\n");
      out.write("            <div class=\"widget no-border m-0\">\r\n");
      out.write("              <ul class=\"list-inline sm-text-center font-12\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">공지사항</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>|</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Help Desk</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>|</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Support</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <a class=\"scrollToTop\" href=\"#\"><i class=\"fa fa-angle-up\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- end wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer Scripts -->\r\n");
      out.write("<!-- JS | Custom script for all pages -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
