/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-11 14:17:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class likesList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Edu/SpringWorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sulJeong/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Edu/SpringWorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sulJeong/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1576160540876L));
    _jspx_dependants.put("jar:file:/C:/Edu/SpringWorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sulJeong/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t//fetchList 제어\r\n");
      out.write("\tlet isEnd = false;\r\n");
      out.write("\tlet flag = true;\r\n");
      out.write("\r\n");
      out.write("\t//contextPath 얻기\r\n");
      out.write("\tfunction getContextPath() {\r\n");
      out.write("\t\tvar hostIndex = location.href.indexOf(location.host) + location.host.length;\r\n");
      out.write("\t\treturn location.href.substring(hostIndex, location.href.indexOf('/', hostIndex + 1));\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//동적으로 추가된 data-countdown에 이벤트 주기\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\t$('.data-countdown').not('.initialized').each(function() {\r\n");
      out.write("\t\t\tvar ac = $(this).addClass('initialized');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('[data-countdown]').each(function() {\r\n");
      out.write("\t\t\tvar $this = $(this), finalDate = $(this).data('countdown');\r\n");
      out.write("\t\t\t$this.countdown(finalDate, function(event) {\r\n");
      out.write("\t\t\t\t$this.html(event.strftime('%D 일 '));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//현재 url\r\n");
      out.write("\t\tvar curUrl = location.href;\r\n");
      out.write("\r\n");
      out.write("\t\t//정렬 조건 변경 시\r\n");
      out.write("\t\t$(\"[name=order]\").on(\"change\", function() {\r\n");
      out.write("\t\t\t$(\"#mailchimp-subscription-form\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//\r\n");
      out.write("\r\n");
      out.write("\t\t//스크롤 시\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tlet $window = $(this);\r\n");
      out.write("\t\t\tlet scrollTop = $window.scrollTop();\r\n");
      out.write("\t\t\tlet windowHeight = $window.height();\r\n");
      out.write("\t\t\tlet documentHeight = $(document).height();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (scrollTop + windowHeight + 30 > documentHeight) {\r\n");
      out.write("\t\t\t\tif(flag)\r\n");
      out.write("\t\t\t\t\tfetchList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//fetchList();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//좋아요 취소 버튼 클릭 시\r\n");
      out.write("\t\t$(document).on(\"click\", \"[type=button]\", function() {\r\n");
      out.write("\t\t\tvar deleted = $(this).parent().parent().parent();\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : getContextPath() + \"/likes/delete\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\tdata : {fundingCode : $(this).val()},\r\n");
      out.write("\t\t\t\tbeforeSend : function(xhr) {   \r\n");
      out.write("\t\t\t\t\t/*데이터를 전송하기 전에 헤더에 csrf값을 설정한다*/\r\n");
      out.write("                    xhr.setRequestHeader(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("                },\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tif(result == 1){\r\n");
      out.write("\t\t\t\t\t\talert(\"내가 좋아한 펀딩에서 삭제됐습니다.\");\r\n");
      out.write("\t\t\t\t\t\tdeleted.remove();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\talert(\"오류 발생\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//ajax End\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//jquery End\r\n");
      out.write("\r\n");
      out.write("\t//리스트 덧붙이기\r\n");
      out.write("\tlet fetchList = function() {\r\n");
      out.write("\t\tflag = false;\r\n");
      out.write("\r\n");
      out.write("\t\tif (isEnd == true)\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\r\n");
      out.write("\t\t//현재 요소 개수\r\n");
      out.write("\t\tvar listCnt = $(\".thumb\").length;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : getContextPath() + \"/mypage/fetchLikesList\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {listCnt : listCnt},\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t}, 500);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlet resultLength = result.length;\r\n");
      out.write("\t\t\t\tif (resultLength < 4)\r\n");
      out.write("\t\t\t\t\tisEnd = true;\r\n");
      out.write("\t\t\t\t$.each(result, function(index, item) {\r\n");
      out.write("\t\t\t\t\trenderList(false, item);\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\talert(\"오류 발생\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//ajax End\r\n");
      out.write("\t}\r\n");
      out.write("\t//fetchList End\r\n");
      out.write("\r\n");
      out.write("\tlet renderList = function(mode, item) {\r\n");
      out.write("\t\tvar per = item.stackPrice / item.goalPrice * 100;\r\n");
      out.write("\t\tlet html = '<div class=\"col-sm-6 col-md-3 wow fadeIn\">';\r\n");
      out.write("\t\thtml += '<div class=\"causes bg-silver-light maxwidth500 mb-30\">';\r\n");
      out.write("\t\thtml += '<div class=\"thumb\">';\r\n");
      out.write("\t\thtml += '<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/funding/' + item.code + '\">';\r\n");
      out.write("\t\thtml += '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/funding/Thumnail_' + item.image + '\" alt=\"\" class=\"img-fullwidth\">';\r\n");
      out.write("\t\thtml += '</a>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '<div class=\"causes-details border-1px bg-white clearfix p-15 pb-30\">';\r\n");
      out.write("\t\thtml += '<h4 class=\"font-16 text-uppercase\">';\r\n");
      out.write("\t\thtml += '<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/funding/' + item.code + '\">'\r\n");
      out.write("\t\t\t\t+ item.title + '</a>';\r\n");
      out.write("\t\thtml += '</h4>';\r\n");
      out.write("\t\thtml += '<ul class=\"list-inline font-weight-600 font-14 clearfix mb-5\">';\r\n");
      out.write("\t\thtml += '<li class=\"pull-left font-weight-400 text-black-333 pr-0\">달성금액:';\r\n");
      out.write("\t\thtml += '<span class=\"text-theme-colored font-weight-700\">'\r\n");
      out.write("\t\t\t\t+ item.stackPrice.toLocaleString() + '원</span>';\r\n");
      out.write("\t\thtml += '</li>';\r\n");
      out.write("\t\thtml += '<li class=\"pull-right font-weight-400 text-black-333 pr-0\">목표금액:';\r\n");
      out.write("\t\thtml += '<span class=\"text-theme-colored font-weight-700\">'\r\n");
      out.write("\t\t\t\t+ item.goalPrice.toLocaleString() + '원</span>';\r\n");
      out.write("\t\thtml += '</li>';\r\n");
      out.write("\t\thtml += '</ul>';\r\n");
      out.write("\t\thtml += '<div class=\"progress-item mt-5\">';\r\n");
      out.write("\t\thtml += '<div class=\"progress mb-0\">';\r\n");
      out.write("\t\thtml += '<div data-percent=\"' + per\r\n");
      out.write("\t\t\t\t+ '\" class=\"progress-bar appeared\" style=\"width: ' + per\r\n");
      out.write("\t\t\t\t+ '%;\">';\r\n");
      out.write("\t\thtml += '<span class=\"percent\">0</span><span class=\"percent\">' + per\r\n");
      out.write("\t\t\t\t+ '%</span>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '<div class=\"pull-left font-weight-400 text-black-333 pr-0\">';\r\n");
      out.write("\t\thtml += '<strong>펀딩종료까지 </strong>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '<div class=\"text-center\" data-countdown=\"' + item.endDate + '\"></div>';\r\n");
      out.write("\t\thtml += '<button type=\"button\" value=\"'+ item.code +'\" class=\"btn btn-default btn-theme-colored mt-10 font-16 btn-sm\">좋아요 취소 <i class=\"fa fa-thumbs-down font-16 ml-5\"></i>';\r\n");
      out.write("\t\thtml += '</button>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\t\thtml += '</div>';\r\n");
      out.write("\r\n");
      out.write("\t\tif (mode)\r\n");
      out.write("\t\t\t$(\"#list-funding\").prepend(html);\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t$(\"#list-funding\").append(html);\r\n");
      out.write("\r\n");
      out.write("\t\tinit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Start main-content -->\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("\t<!-- Section: inner-header -->\r\n");
      out.write("\t<section class=\"inner-header divider layer-overlay overlay-dark-8\"\r\n");
      out.write("\t\tdata-bg-img=\"http://placehold.it/1920x1280\">\r\n");
      out.write("\t\t<div class=\"container pt-90 pb-40\">\r\n");
      out.write("\t\t\t<!-- Section Content -->\r\n");
      out.write("\t\t\t<div class=\"section-content\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"text-white font-36\">내가 좋아한 펀딩</h2>\r\n");
      out.write("\t\t\t\t\t\t<!-- <ol class=\"breadcrumb text-left mt-10 white\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Pages</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\">Causes Grid</li>\r\n");
      out.write("\t\t\t\t\t\t</ol> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Section: Causes -->\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container pt-40 pb-40\">\r\n");
      out.write("\t\t\t<div class=\"section-content\">\r\n");
      out.write("\t\t\t\t<div class=\"row multi-row-clearfix\" id=\"list-funding\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- end main-content -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/mypage/likesList.jsp(199,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(list) == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<section class=\"bg-white-f12 exists\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"container pb-0\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"section-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <h5 class=\"sub-title\">Sub Title Here</h5> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"title\">아직 좋아한 펀딩이 없습니다.</h2>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>다양한 전통주가 회원님의 후원을 기다립니다!</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/funding\" class=\"btn btn-dark btn-theme-colored btn-lg mt-20\">펀딩 보러가기 <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</section>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/mypage/likesList.jsp(218,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/likesList.jsp(218,5) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/mypage/likesList.jsp(218,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("fundingList");
      // /WEB-INF/views/mypage/likesList.jsp(218,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"causes bg-silver-light maxwidth500 mb-30\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"thumb\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/funding/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/funding/Thumnail_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\" class=\"img-fullwidth\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"causes-details border-1px bg-white clearfix p-15 pb-30\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"font-16 text-uppercase\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/funding/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</h4>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-inline font-weight-600 font-14 clearfix mb-5\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"pull-left font-weight-400 text-black-333 pr-0\">달성금액:\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"text-theme-colored font-weight-700\">");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("원</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"pull-right font-weight-400 text-black-333 pr-0\">목표금액:\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"text-theme-colored font-weight-700\">");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("원</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-item mt-5\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress mb-0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div data-percent=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.stackPrice/fundingList.goalPrice *100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"progress-bar appeared\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.stackPrice/fundingList.goalPrice *100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"percent\">0</span><span class=\"percent\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.stackPrice / fundingList.goalPrice * 100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-left font-weight-400 text-black-333 pr-0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<strong>펀딩종료까지 </strong>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"text-center\" data-countdown=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t$(document).ready(function() {\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t$('[data-countdown]').each(function() {\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar $this = $(this), finalDate = $(this).data('countdown');\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t$this.countdown(finalDate, function(event) {\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$this.html(event.strftime('%D 일'));\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</script>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-default btn-theme-colored mt-10 font-16 btn-sm\">좋아요 취소\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-thumbs-down font-16 ml-5\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_eval_fmt_005fformatNumber_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fformatNumber_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          _jspx_push_body_count_c_005fforEach_005f0[0]++;
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fformatNumber_005f0);
        }
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.stackPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          int evalDoAfterBody = _jspx_th_fmt_005fformatNumber_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fformatNumber_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
          _jspx_push_body_count_c_005fforEach_005f0[0]--;
        }
      }
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_eval_fmt_005fformatNumber_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fformatNumber_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          _jspx_push_body_count_c_005fforEach_005f0[0]++;
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fformatNumber_005f1);
        }
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fundingList.goalPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          int evalDoAfterBody = _jspx_th_fmt_005fformatNumber_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fformatNumber_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
          _jspx_push_body_count_c_005fforEach_005f0[0]--;
        }
      }
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }
}
