/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-15 13:48:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1576310964000L));
    _jspx_dependants.put("jar:file:/C:/Edu/SpringWorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sulJeong/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar popAuthEmail = null;\r\n");
      out.write("\tvar emailAuthResult=null;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goPopup() {\r\n");
      out.write("\t\t//경로는 시스템에 맞게 수정하여 사용\r\n");
      out.write("\t\t//호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 \r\n");
      out.write("\t\t//호출하게 됩니다. \r\n");
      out.write("\t\tvar pop = window.open(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/juso/jusoPopup\", \"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\t\t//** 2017년 5월 모바일용 팝업 API 기능 추가제공 **/ \r\n");
      out.write("\t\t// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 \r\n");
      out.write("\t\t// 실제 주소검색 URL(http://www.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다. \r\n");
      out.write("\t\t// var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goAuthPopup() {\r\n");
      out.write("\t\tvar popAuth = window.open(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/identity/identityAuth\", \"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction emailAuthPopup() {\r\n");
      out.write("\t\tpopAuthEmail = window.open(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/identity/emailAuth\", \"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\t\t//popAuthEmail.document.getElementById(\"childEmailAuth\").value = document.getElementById('childEmailAuth').value;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction jusoCallBack(roadFullAddr, addrDetail, jibunAddr) {\r\n");
      out.write("\t\t//alert(1)\r\n");
      out.write("\t\t// 2017년 2월 제공항목이 추가되었습니다. 원하시는 항목을 추가하여 사용하시면 됩니다. \r\n");
      out.write("\t\t\t//document.form.addr.value = roadFullAddr +\" \"+ addrDetail;\r\n");
      out.write("\t\tdocument.form.addr.value = roadFullAddr;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar status = '0'; //아이디 중복체크 상태변수\r\n");
      out.write("\t\tvar authStatus = '3';//성인인증 상태변수\r\n");
      out.write("\t\tvar flage = false; // 비밀번호 일치 여부\r\n");
      out.write("\t\tvar emailStatus = 'false'; //이메일 수신 동의 여부\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#idDuplicateCheck\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#id').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#id').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar idVal = $(\"#id\").val()\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar allDate = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+\"&id=\"+idVal;\r\n");
      out.write("\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t\t url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/idDuplicateCheck\", //서버요청주소\r\n");
      out.write("\t\t\t\t\t type:\"post\", //요청방식(get|post|put:patch:delete)\r\n");
      out.write("\t\t\t\t\t dataType:\"json\", //서버가 보내온 데이터 타입(text,html,xml,json)\r\n");
      out.write("\t\t\t\t\t data: allDate ,//서버에게 보내는 parameter 정보\r\n");
      out.write("\t\t\t\t\t success:function(result){\r\n");
      out.write("\t\t\t\t\t\t alert(\"중복된 ID 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t $(\"#id\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t $(\"#id\").focus();\r\n");
      out.write("\t\t\t\t\t\t status = '0';\r\n");
      out.write("\t\t\t\t\t } ,//성공했을대\r\n");
      out.write("\t\t\t\t\t error:function(err){\r\n");
      out.write("\t\t\t\t\t\t $(\"#idDuplicateCheck\").val(\"중복체크완료\");\r\n");
      out.write("\t\t\t\t\t\t status = '1';\r\n");
      out.write("\t\t\t\t\t }//오류발생했을때\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#pwdCheck').keyup(function(){\r\n");
      out.write("\t\t\t  if($('#pwdCheck').val()!=$('#pwd').val()){\r\n");
      out.write("\t\t\t    $('#pwdEqualCheck').text('');\r\n");
      out.write("\t\t\t    $('#pwdEqualCheck').html(\"암호가 일치하지 않습니다. 다시 확인해주세요.\").css(\"color\",\"red\"); \r\n");
      out.write("\t\t\t    flage = false;\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t    $('#pwdEqualCheck').text('');\r\n");
      out.write("\t\t\t    $('#pwdEqualCheck').html(\"암호가 일치합니다.\").css(\"color\",\"blue\");\r\n");
      out.write("\t\t\t    flage = true;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#register\").click(function() {\r\n");
      out.write("\t\t\tif($('#name').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"성함을 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#name').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#id').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#id').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($('#pwd').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#pwd').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#email').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#email').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#phone').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"전화번호를 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#phone').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#addr').val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"주소를 입력해주세요\");\r\n");
      out.write("\t\t\t\t$('#addr').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#hidden').val()=='true'){\r\n");
      out.write("\t\t\t    authStatus = '4';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#emailCheckStatus').val()=='true'){\r\n");
      out.write("\t\t\t    emailStatus = 'true';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t if(status == '0'){\r\n");
      out.write("\t\t\t\t  alert(\"아이디 중복체크를 해주세요\");\r\n");
      out.write("\t\t\t\t  return false;\r\n");
      out.write("\t\t\t  }else if(flage == false){\r\n");
      out.write("\t\t\t\t  alert(\"비밀번호 일치 여부 확인해주세요.\");\r\n");
      out.write("\t\t\t\t  return false;\r\n");
      out.write("\t\t\t  }else if(emailStatus == 'false'){\r\n");
      out.write("\t\t\t\t  alert(\"이메일 인증 후 회원가입 가능\");\r\n");
      out.write("\t\t\t\t  return false;\r\n");
      out.write("\t\t\t  }else if(authStatus == '3'){\r\n");
      out.write("\t\t\t\t  alert(\"성인인증을 해주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t  return false;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#emailCheck\").click(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#email\").val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"이메일을 입력해주세요.\")\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar emailVal = $(\"#email\").val()\r\n");
      out.write("\t\t\tvar allDate = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+\"&email=\"+emailVal;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t\t url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/auth\", //서버요청주소\r\n");
      out.write("\t\t\t\t\t type:\"post\", //요청방식(get|post|put:patch:delete)\r\n");
      out.write("\t\t\t\t\t dataType:\"text\", //서버가 보내온 데이터 타입(text,html,xml,json)\r\n");
      out.write("\t\t\t\t\t data: allDate ,//서버에게 보내는 parameter 정보\r\n");
      out.write("\t\t\t\t\t success:function(result){\r\n");
      out.write("\t\t\t\t\t\t //alert(result);\r\n");
      out.write("\t\t\t\t\t\t $(\"#hidden2\").val(result);\r\n");
      out.write("\t\t\t\t\t\t emailAuthPopup();\r\n");
      out.write("\t\t\t\t\t } ,//성공했을대\r\n");
      out.write("\t\t\t\t\t error:function(err){\r\n");
      out.write("\t\t\t\t\t\talert(\"실패\")\r\n");
      out.write("\t\t\t\t\t\temailStatus = 'false';\r\n");
      out.write("\t\t\t\t\t }//오류발생했을때\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\tfunction CheckForm(join) {\r\n");
      out.write("\t\tif ($('input:checkbox[id=emailAccept]').is(':checked') == false) {\r\n");
      out.write("\t\t\t$('[id=emailAccept]').attr('value', '0');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($('input:checkbox[id=emailAccept]').is(':checked') == true) {\r\n");
      out.write("\t\t\t$('[id=emailAccept]').attr('value', '1');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-6 col-md-push-3\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/form/memberJoinForm.jsp(196,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result==false}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<h3>성인인증 실패로 회원가입을 할 수 없습니다.</h3>\r\n");
          out.write("\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t<button class=\"btn btn-dark btn-lg btn-block mt-15\" type=\"submit\" id=\"register\" name=\"register\" onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/'\">메인 페이지로 가기</button>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<form name=\"form\" id=\"reg-form\" class=\"register-form\" method=\"post\"\r\n");
          out.write("\t\t\t\taction=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/memberJoin\"\r\n");
          out.write("\t\t\t\tonsubmit=\"return CheckForm(this)\">\r\n");
          out.write("\t\t\t\t<!-- 스프링 security 4에선 POST 전송시무조건 csrt 를 보내야 한다. (GET은 안보내도 됨)-->\r\n");
          out.write("\t\t\t\t<input type=\"hidden\" name=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\tvalue=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t<div class=\"icon-box mb-0 p-0\">\r\n");
          out.write("\t\t\t\t\t<a href=\"#\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"icon icon-bordered icon-rounded icon-sm pull-left mb-0 mr-10\">\r\n");
          out.write("\t\t\t\t\t\t<i class=\"pe-7s-users\"></i>\r\n");
          out.write("\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t<h4 class=\"text-gray pt-10 mt-0 mb-30\">Don't have an Account?\r\n");
          out.write("\t\t\t\t\t\tRegister Now.</h4>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<hr>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>Name</label> <input name=\"name\" id=\"name\"\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label for=\"form_choose_username\">Choose UserID</label> <input\r\n");
          out.write("\t\t\t\t\t\t\tid=\"id\" name=\"id\" class=\"form-control\" type=\"text\" >\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>아이디 중복 체크</label> <input type=\"button\" value=\"중복체크\"\r\n");
          out.write("\t\t\t\t\t\t\tname=\"idDuplicateCheck\" id=\"idDuplicateCheck\" class=\"form-control\" required=\"required\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label for=\"form_choose_password\">Choose Password</label> <input\r\n");
          out.write("\t\t\t\t\t\t\tid=\"pwd\" name=\"pwd\" class=\"form-control\" type=\"password\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>Re-enter Password</label> <input id=\"pwdCheck\"\r\n");
          out.write("\t\t\t\t\t\t\tname=\"pwdCheck\" class=\"form-control\" type=\"password\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\" id=\"pwdEqualCheck\">비밀번호 확인</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>Email Address</label> \r\n");
          out.write("\t\t\t\t\t\t<input name=\"email\" id=\"email\" class=\"form-control\" type=\"email\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>인증하기</label> \r\n");
          out.write("\t\t\t\t\t\t<input name=\"emailCheck\" id=\"emailCheck\" class=\"form-control\" type=\"button\" value=\"Email Address 인증\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>휴대폰</label> <input name=\"phone\" id=\"phone\"\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>생년월일 성인인증</label> \r\n");
          out.write("\t\t\t\t\t\t<input type=\"button\" value=\"성인인증\" name=\"Authenticate\" id=\"Authenticate\" onClick=\"goAuthPopup();\" class=\"form-control\" required=\"required\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label for=\"form_choose_password\">주소</label> \r\n");
          out.write("\t\t\t\t\t\t<input id=\"addr\"\r\n");
          out.write("\t\t\t\t\t\t\tname=\"addr\" class=\"form-control\" type=\"text\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t<label>주소 찾기</label> \r\n");
          out.write("\t\t\t\t\t\t<input id=\"addrBtn\" name=\"addrBtn\" class=\"form-control\" type=\"button\" onClick=\"goPopup();\" value=\"나의 주소지 찾기\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group col-md-12\">\r\n");
          out.write("\t\t\t\t\t\t<label for=\"form_choose_username\">이메일 수신동의(선택)</label> <input\r\n");
          out.write("\t\t\t\t\t\t\tid=\"emailAccept\" name=\"emailAccept\" type=\"checkbox\" value=\"\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t<button class=\"btn btn-dark btn-lg btn-block mt-15\" type=\"submit\"\r\n");
          out.write("\t\t\t\t\t\tid=\"register\" name=\"register\">Register Now</button>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</form>\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t<input type=\"hidden\" id=\"hidden\" name=\"hidden\">\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t<input type=\"hidden\" id=\"hidden2\" name=\"hidden2\">\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t<input type=\"hidden\" id=\"emailCheckStatus\" name=\"emailCheckStatus\">\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
