/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-12 15:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchLoginInfoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#loginGoBtn\").hide();\r\n");
      out.write("\t$(\"#find\").click(function(){\r\n");
      out.write("\t\tif($(\"#name1\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"성함을 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#name1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#phone1\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"핸드폰 번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#phone1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar nameVal = $(\"#name1\").val()\r\n");
      out.write("\t\tvar phoneVal = $(\"#phone1\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar allDate = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+\"&name=\"+nameVal +\"&phone=\"+phoneVal;\r\n");
      out.write("\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t url: \"findId\", //서버요청주소\r\n");
      out.write("\t\t\t\t type:\"post\", //요청방식(get|post|put:patch:delete)\r\n");
      out.write("\t\t\t\t dataType:\"json\", //서버가 보내온 데이터 타입(text,html,xml,json)\r\n");
      out.write("\t\t\t\t data: allDate ,//서버에게 보내는 parameter 정보\r\n");
      out.write("\t\t\t\t success:function(result){\r\n");
      out.write("\t\t\t\t    //$(\"#showId\").html(result.name+\"님의 아이디는 \"+result.id+\"입니다.\")\r\n");
      out.write("\t\t\t\t    $(\"#login-form\").hide();\r\n");
      out.write("\t\t\t\t    var str=\"\";\r\n");
      out.write("\t\t\t\t\t$.each(result, function(index, item){\r\n");
      out.write("\t\t\t\t\t\tstr+=item.name+\"님의 아이디는 \"+item.id+\"입니다.<br>\";\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#showId\").html(str);\r\n");
      out.write("\t\t\t\t\t$(\"#loginGoBtn\").show();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t } ,//성공했을대\r\n");
      out.write("\t\t\t\t error:function(err){\r\n");
      out.write("\t\t\t\t\t $(\"#showId\").html(\"입력하신 정보의 아이디는 존재하지 않습니다.\")\r\n");
      out.write("\t\t\t\t }//오류발생했을때\r\n");
      out.write("\t\t\t }); \r\n");
      out.write("\t  });\r\n");
      out.write("\t\r\n");
      out.write("\t $(\"#findPWD\").click(function(){\r\n");
      out.write("\t\tif($('#name').val()==\"\"){\r\n");
      out.write("\t\t\talert(\"성함을 입력해주세요\");\r\n");
      out.write("\t\t\t$('#name').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('#phone').val()==\"\"){\r\n");
      out.write("\t\t\talert(\"핸드폰 번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$('#phone').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('#email').val()==\"\"){\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t\t$('#email').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t  }); \r\n");
      out.write("\t \r\n");
      out.write("\t if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result>0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("\t\t\talert(\"임시 비밀번호를 이메일로 전송하였습니다.\")\r\n");
      out.write("\t\t}else if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result==0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("\t\t\talert(\"입력 정보를 다시 확인해주세요\");\r\n");
      out.write("\t\t\t$('#name').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<ul id=\"myTab\" class=\"nav nav-tabs boot-tabs\">\r\n");
      out.write("  <li class=\"active\"><a href=\"#home\" data-toggle=\"tab\">아이디 찾기</a></li>\r\n");
      out.write("  <li><a href=\"#profile\" data-toggle=\"tab\">비밀번호 찾기</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("  <div class=\"tab-pane fade in active\" id=\"home\">\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("\t<section>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 col-md-push-3\">\r\n");
      out.write("            <h4 class=\"text-gray mt-0 pt-5\"> 아이디 찾기</h4>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <form id=\"login-form\" name=\"login-form\" class=\"clearfix\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loginCheck\" method=\"post\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"form-group col-md-12\">\r\n");
      out.write("                  <label for=\"form_username_email\">Name</label>\r\n");
      out.write("                  <input id=\"name1\" name=\"name1\" class=\"form-control\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"form-group col-md-12\">\r\n");
      out.write("                  <label for=\"form_password\">Phone</label>\r\n");
      out.write("                  <input id=\"phone1\" name=\"phone1\" class=\"form-control\" type=\"text\" >\r\n");
      out.write("                </div>\r\n");
      out.write("               <div class=\"form-group pull-right mt-10\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-dark btn-sm\" id=\"find\" value=\"Login\">찾기</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </form>\r\n");
      out.write("            <div id=\"showId\">\r\n");
      out.write("            \t\r\n");
      out.write("              </div>\r\n");
      out.write("              </p>\r\n");
      out.write("              </p>\r\n");
      out.write("              <a id=\"loginGoBtn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"btn btn-dark btn-circled\">로그인</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"tab-pane fade\" id=\"profile\">\r\n");
      out.write("  \t<div class=\"main-content\">\r\n");
      out.write("\t<section>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 col-md-push-3\">\r\n");
      out.write("            <h4 class=\"text-gray mt-0 pt-5\"> 비밀번호 찾기</h4>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <form id=\"login-form\" name=\"login-form\" class=\"clearfix\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pwdCheck\" method=\"post\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"form-group col-md-12\">\r\n");
      out.write("                  <label for=\"form_username_email\">id</label>\r\n");
      out.write("                  <input id=\"name\" name=\"id\" class=\"form-control\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"form-group col-md-12\">\r\n");
      out.write("                  <label for=\"form_password\">Phone</label>\r\n");
      out.write("                  <input id=\"phone\" name=\"phone\" class=\"form-control\" type=\"text\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group col-md-12\">\r\n");
      out.write("                  <label for=\"form_password\">email</label>\r\n");
      out.write("                  <input id=\"email\" name=\"email\" class=\"form-control\" type=\"text\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("               <div class=\"form-group pull-right mt-10\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-dark btn-sm\" id=\"findPWD\" value=\"Login\">찾기</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <div id=\"showId2\">\r\n");
      out.write("                \r\n");
      out.write("              </div> -->\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
